package-lock.json
package.json

Added the React Hook Form v7.34.2 Library

ESLG-29: Added React Hook Form

---

package-lock.json
package.json
pages/basketball/user-form.tsx

Created initial code for user form using React Hook Forms

ESLG-11: Added User Form

---

jest.config.js
package-lock.json
package.json

Added the following:
- testing-library/jest-dom v5.16.5
- testing-library/react v13.3.0
- jest v29.0.1
- jest-environment-jsdom v29.0.1

ESLG-7: Added JEST and React-Testing Library

---

pages/basketball/user-form.tsx

- Changed the submit button from input button to Material UI
- Added margins between fields

ESLG-34: Modified user form styling

---

pages/basketball/terms-conditions.tsx

Implemented initial code for Terms and Conditions Page

ESLG-15: Added Terms and Conditions Page

---

next.config.js
package-lock.json
pages/api/basketball.js
pages/basketball/rewards-message.tsx
pages/basketball/terms-conditions.tsx
pages/basketball/user-form.tsx
public/assets/basketball/css/font-loader.css
public/assets/basketball/play.html

Applied prettier to all files in the project, ensuring that every file in the project is formatted accordingly.

ESLG-37: apply prettier formatting to all files

---

public/assets/basketball/play.html

Added styling to canvas that renders the game that will vertically center it.

ESLG-42: Added styling to game canvas to make it center vertically

---

apps/client/public/assets/basketball/play.html

- Added code to detect if browser used is safari
- Added code that evaluates whether or not to load audio based on a gameParam

ESLG-48: Added code that disables audio for safari browser

---

apps/client/next.config.js

Added redirect configuration to next.config.js

ESLG-49: Added a configuration where the base URL will now redirect to /basketball/terms-conditions

---

apps/client/pages/basketball/rewards-message.tsx
apps/client/pages/basketball/terms-conditions.tsx
apps/client/pages/basketball/user-form.tsx
apps/client/public/assets/basketball/play.html

- Has a working localStorage Set and Get
- Re-routes to previous pages based on lacking requirements
- (i.e. accessing "basketball/play" without filling out the form redirects to "basketball/user-form")

ESLG-43: Setup Page Re-routes based on Game Requirements

---

apps/client/pages/basketball/terms-conditions.tsx

- Made changes to terms and conditions page layout for better mobile experience
- Removed lorem ipsum
- Removed previous basketball header image

ESLG-45: Modified Terms and Conditions for Mobile Responsiveness

---

apps/client/pages/basketball/rewards-message.tsx
apps/client/pages/basketball/rewards-select.tsx
apps/client/public/assets/basketball/play.html

- Also modified play.html to redirect to it after game over

ESLG-54: Added rewards-select page and adjusted other pages to fit it on the user flow

---

apps/client/pages/basketball/rewards-select.tsx
apps/client/pages/basketball/user-form.tsx
apps/client/public/assets/basketball/play.html

- Adjusted layout for User Form page to fit mobile devices
- Moved Terms and Conditions to the User Form Page
- Refactored re-routing from Terms-Conditions to User-Form

ESLG-58: Adjust Mobile Layout for User Form

---

apps/client/pages/basketball/rewards-select.tsx

- Adjusted layout for Rewards Select page to fit mobile devices
- Removed redirect to Terms Conditions page

ESLG-59: Adjust Mobile Layout for Rewards Select

---

apps/client/pages/basketball/rewards-message.tsx

- Adjusted layout for Rewards Message page to fit mobile devices
- Removed redirect to Terms Conditions page
- Reward is loaded dynamically based on selected merchant/reward from Rewards Select

ESLG-56: Adjust Mobile Layout for Rewards Message

---

apps/server/getRewards.ts
apps/server/serverless.yml

Created endpoint for get rewards which accepts the following parameters:
- Score
- Reward Type
The endpoint returns reward id and reward code.
_You can add screenshots and or screen recordings in this section_

ESLG-25 http endpoint get game rewards

---

package.json
yarn.lock

- installed package axios v1.1.2

ESLG-63: Added Axios v1.1.2

---

apps/server/userInformation.ts

Modified Endpoint User Info
- Now returns insertId
- { id: insertId }

ESLG-61: Fixed Return for User Info Endpoint

---

apps/server/getRewards.ts

- removed reward type as parameter for getting available rewards
- removed reward type as parameter for getting available rewards

ESLG-25: Modified Query for Getting Available Rewards

---

package.json

Merged lodash package installation

Merge lodash package installation

---

apps/server/userTransaction.ts

Fixed the Reference Number logic by fixing the variable for the today's date.

ESLG-62: Faulty Reference Number logic

---

package.json

build: add lodash package v4.17.21

ESLG-50: Added lodash package v4.17.21

---

apps/client/pages/basketball/rewards-message.tsx
apps/client/pages/basketball/rewards-select.tsx

- Integrated "/userTran" endpoint to Rewards Select/Message page
- Successfully retrieves all available unredeemed rewards in the database

ESLG-67: Rewards Message Integrated Endpoint

---

.gitignore
apps/server/package.json
apps/server/serverless.yml
yarn.lock

- Installed Serverless Domain Manager
- Created Dev Stage
- Deployed working Dev Stage

ESLG-69: Added Serverless Domain Manager v6.1.0
